<?php

namespace Psdtg\SiteBundle\Extension;

use Psdtg\SiteBundle\Entity\Circuits\PhoneCircuit;
use Psdtg\SiteBundle\Entity\Requests\Request;
use Psdtg\SiteBundle\Entity\Requests\NewCircuitRequest;
use Psdtg\SiteBundle\Entity\Requests\RemoveCircuitRequest;
use Psdtg\SiteBundle\Entity\Requests\ChangeConnectivityTypeRequest;
use Psdtg\SiteBundle\Entity\Requests\ActivateServiceRequest;

class RequestService {
    public function approveRequest(Request $request) {
        $methods = get_class_methods($this);
        $requestClass = get_class($request);
        foreach($methods as $curMethod) {
            $cutMethod = substr($curMethod, 7);
            if($cutMethod != 'Request' && strpos($requestClass, $cutMethod) !== false) {
                return $this->$curMethod($request);
            }
        }
        throw new \Exception('Method not found');
    }

    protected function approveNewCircuitRequest(NewCircuitRequest $request) {
        $circuit = new PhoneCircuit();
        $circuit->setNewCircuitRequest($request);
        $circuit->setConnectivityType($request->getConnectivityType());
        $circuit->setUnit($request->getUnit());
        $circuit->setBandwidthProfile($request->getBandwidthProfile());
        $circuit->setPaidByPsd(true);
        $circuit->setComments($request->getComments());
        $request->setCircuit($circuit);
    }

    protected function approveRemoveCircuitRequest(RemoveCircuitRequest $request) {
        $request->getCircuit()->setDeletedAt(new \DateTime('now'));
    }

    protected function approveChangeConnectivityTypeRequest(ChangeConnectivityTypeRequest $request) {
        $request->getCircuit()->setConnectivityType($request->getNewConnectivityType());
        $request->getCircuit()->setBandwidthProfile($request->getNewBandwidthProfile());
    }

    protected function approveActivateServiceRequest(ActivateServiceRequest $request) {
        $circuit = new PhoneCircuit();
        $circuit->setNumber($request->getNumber());
        $circuit->setConnectivityType($request->getNewConnectivityType());
        $circuit->setUnit($request->getUnit());
        $circuit->setBandwidthProfile($request->getNewBandwidthProfile());
        $circuit->setPaidByPsd(false);
        $circuit->setComments('Generated by ActivateServiceRequest '.$request->getId());
        $request->setCircuit($circuit);
    }
}
?>
