<?php

namespace Kp\UserBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Kp\UserBundle\Wantlet\ORM\Point;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Kp\SiteBundle\Entity\Repositories\BaseRepository
{
}
